package sandbox

import (
	"encoding/json"
	"fmt"
	"strings"

	"github.com/forgia-labs/forgia/internal/guardrails"
)

// SeccompProfile represents a Docker seccomp profile.
// Simplified — focuses on blocking specific executables via path-based rules.
type SeccompProfile struct {
	DefaultAction string          `json:"defaultAction"`
	Syscalls      []SeccompRule   `json:"syscalls,omitempty"`
	Comment       string          `json:"comment,omitempty"`
	BlockedPaths  []string        `json:"blockedPaths,omitempty"` // informational, not Docker-native
}

// SeccompRule defines a syscall filter rule.
type SeccompRule struct {
	Names  []string `json:"names"`
	Action string   `json:"action"`
	Args   []any    `json:"args,omitempty"`
}

// GenerateSeccompJSON converts guardrails deny patterns into a Docker seccomp profile.
// This is a best-effort mapping — seccomp operates at syscall level, not file path level.
// For file path restrictions, volume mounts are the primary enforcement mechanism.
// The seccomp profile blocks dangerous syscalls that agents shouldn't need.
func GenerateSeccompJSON(g *guardrails.Guardrails) ([]byte, error) {
	profile := SeccompProfile{
		DefaultAction: "SCMP_ACT_ALLOW", // allow by default, deny specific
		Comment:       "Generated by Forgia from deny.toml",
	}

	// Block dangerous syscalls that an AI agent should never need.
	profile.Syscalls = []SeccompRule{
		{
			// Block ptrace — no debugging host processes.
			Names:  []string{"ptrace"},
			Action: "SCMP_ACT_ERRNO",
		},
		{
			// Block kernel module loading.
			Names:  []string{"init_module", "finit_module", "delete_module"},
			Action: "SCMP_ACT_ERRNO",
		},
		{
			// Block mount/umount — no filesystem manipulation.
			Names:  []string{"mount", "umount2"},
			Action: "SCMP_ACT_ERRNO",
		},
		{
			// Block reboot/shutdown.
			Names:  []string{"reboot"},
			Action: "SCMP_ACT_ERRNO",
		},
		{
			// Block setting hostname — container identity.
			Names:  []string{"sethostname", "setdomainname"},
			Action: "SCMP_ACT_ERRNO",
		},
		{
			// Block keyctl — kernel keyring access.
			Names:  []string{"keyctl", "add_key", "request_key"},
			Action: "SCMP_ACT_ERRNO",
		},
	}

	// Extract blocked paths from deny.toml for documentation.
	// Actual file-level enforcement is via volume mounts (not seccomp).
	var blockedPaths []string
	for _, p := range g.Read.Patterns {
		if !strings.HasPrefix(p, "!") {
			blockedPaths = append(blockedPaths, p)
		}
	}
	for _, p := range g.Write.Patterns {
		if !strings.HasPrefix(p, "!") {
			blockedPaths = append(blockedPaths, p)
		}
	}
	profile.BlockedPaths = blockedPaths

	data, err := json.MarshalIndent(profile, "", "  ")
	if err != nil {
		return nil, fmt.Errorf("marshal seccomp profile: %w", err)
	}
	return data, nil
}

// WorkspaceMounts returns the mount configuration for a sandboxed execution.
// Only the workspace is mounted read-write. Sensitive host directories are excluded.
func WorkspaceMounts(workspaceDir string) []Mount {
	return []Mount{
		{
			Source:   workspaceDir,
			Target:   "/workspace",
			ReadOnly: false,
		},
	}
}

// ExcludedHostPaths returns host paths that must NEVER be mounted in the sandbox.
func ExcludedHostPaths() []string {
	return []string{
		"~/.ssh",
		"~/.gnupg",
		"~/.aws",
		"~/.azure",
		"~/.gcloud",
		"~/.password-store",
		"~/.vaults",
		"~/.docker/config.json",
		"~/.netrc",
		"~/.npmrc",
		"~/.pypirc",
		"~/.config/gh",   // TM-4: GitHub CLI tokens
		"~/.kube",        // TM-4: Kubernetes credentials
		"~/.claude",      // TM-4: Claude OAuth tokens (unless sandbox_mount_claude)
	}
}
